### ISSUE TITLE
Will be great if updated to latest Angular

### ISSUE THREAD

**Issue by samahudin** [M4R1KU/ng-dynamic-modules#2]
Thanks Mario for this great tutorial! 
It will be great if you can make a leaner and straight forward version without Material theme, forms etc., so that it will be very useful for other framework users like Ionic. Also if it can be done with the latest Angular 9.
Thanks!

**Comment by M4R1KU** [comment]
Hi @samahudin 

I finally had time to update the project and it is now on Angular 11. 😄 
Regarding your suggestion to make a leaner version: `module-a` would be just that. It does not have any dependencies to such libraries. Angular Material in `module-b` can be seen as a placeholder for any library. Just ignore the parts you don't need, they are mostly not necessary.

I hope I could help 😄
